MODEL_NAMES = {'large': "openai/whisper-large-v2",
               'medium': 'openai/whisper-medium',
               'base': 'openai/whisper-base'}

SAMPLING_RATE = 16000
CHUNK_SIZE = 2  # a size in seconds of one piece of audio used for one subtitles frame
BATCH_SIZE = 30  # how many chunks are passed to a model at once
LIKELIHOOD_TRESHOLD = 0.5  # threshold value for eliminating phrases that contains out-of-dictionary words

SUPPORTED_FORMATS = {'.wav', '.mp4', '.avi', '.webm'}
SUPPORTED_LANGS = {
  "english",
  "chinese",
  "german",
  "spanish",
  "russian",
  "korean",
  "french",
  "japanese",
  "portuguese",
  "turkish",
  "polish",
  "catalan",
  "dutch",
  "arabic",
  "swedish",
  "italian",
  "indonesian",
  "hindi",
  "finnish",
  "vietnamese",
  "hebrew",
  "ukrainian",
  "greek",
  "malay",
  "czech",
  "romanian",
  "danish",
  "hungarian",
  "tamil",
  "norwegian",
  "thai",
  "urdu",
  "croatian",
  "bulgarian",
  "lithuanian",
  "latin",
  "maori",
  "malayalam",
  "welsh",
  "slovak",
  "telugu",
  "persian",
  "latvian",
  "bengali",
  "serbian",
  "azerbaijani",
  "slovenian",
  "kannada",
  "estonian",
  "macedonian",
  "breton",
  "basque",
  "icelandic",
  "armenian",
  "nepali",
  "mongolian",
  "bosnian",
  "kazakh",
  "albanian",
  "swahili",
  "galician",
  "marathi",
  "punjabi",
  "sinhala",
  "khmer",
  "shona",
  "yoruba",
  "somali",
  "afrikaans",
  "occitan",
  "georgian",
  "belarusian",
  "tajik",
  "sindhi",
  "gujarati",
  "amharic",
  "yiddish",
  "lao",
  "uzbek",
  "faroese",
  "creole",
  "pashto",
  "turkmen",
  "nynorsk",
  "maltese",
  "sanskrit",
  "luxembourgish",
  "myanmar",
  "tibetan",
  "tagalog",
  "malagasy",
  "assamese",
  "tatar",
  "hawaiian",
  "lingala",
  "hausa",
  "bashkir",
  "javanese",
  "sundanese"
}
